env:
  node: true
  es6: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2021
  sourceType: module
rules: {
  "no-undef": 0,
  "no-unused-vars": 0,
  "no-case-declarations": 0,
  "no-constant-condition": 0
}
